# Generated by Django 2.0.1 on 2018-03-15 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_regulate_pH', models.BooleanField(default=False)),
                ('low_pH', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high_pH', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pH_adj_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_pH_change', models.DateTimeField(blank=True, null=True)),
                ('auto_regulate_nutrients', models.BooleanField(default=False)),
                ('low_EC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high_EC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nutrient_adj_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_nutrient_change', models.DateTimeField(blank=True, null=True)),
                ('auto_regulate_ORP', models.BooleanField(default=False)),
                ('low_ORP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high_ORP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ORP_adj_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_ORP_change', models.DateTimeField(blank=True, null=True)),
                ('min_change_interval', models.IntegerField(default=60)),
                ('polling_range', models.IntegerField(default=60)),
                ('minimun_data_count', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('exec_time', models.DateTimeField(blank=True, null=True)),
                ('arg1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arg2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WasteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_water_change', models.BooleanField(default=False)),
                ('last_water_change', models.DateTimeField(blank=True, null=True)),
                ('maximum_water_change_interval', models.IntegerField(default=31)),
                ('minimum_water_change_interval', models.IntegerField(default=1)),
                ('auto_pump', models.BooleanField(default=False)),
                ('auto_refill', models.BooleanField(default=False)),
                ('resevoir_volume', models.IntegerField(default=27)),
                ('basin_volume', models.IntegerField(default=27)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=1, on_delete=True, to='hydro.Status'),
        ),
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.ForeignKey(on_delete=True, to='hydro.RequestType'),
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.ForeignKey(on_delete=True, to='hydro.DataType'),
        ),
    ]
